### ISSUE TITLE
Allow database schema changes without losing data

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#254]
As we develop the application, we will need to continue to change the database schema. So far, those changes have been part of making the application deployable at all, with the change from Oracle to PostgreSQL (#1) and the change from WebSphere to WildFly (#2). Under those circumstances, and with only developers practically able to deploy the application, it was fine to completely drop and recreate the database on every change.

Now that the application is deployable, and other people are using it, we need to start thinking about how to make these schema changes in a friendlier way. This will be particularly critical once we have production deployments, as obviously we cannot ask people to throw away their existing data! Manual deployment steps require extensive documentation and are prone to error, so we should automate the deployment as much as is possible.

This will also help us with continuous deployment (#222), as a sandbox that gets wiped multiple times per day (with every merge to master) could be frustrating to use.

---

- [x] Decide on migration strategy: Liquibase
- [x] Allow manual migrations
- [x] Document how to run manual migrations
- [x] Convert contents of `seed.sql` and `jbpm.sql` to new migration language
- [x] Automatically run migrations in our CD environment
- [ ] Announce resolution of this issue on the mailing list

**Comment by jasonaowen** [comment]
@jvasile and I had talked about using [Liquibase](http://www.liquibase.org/) for migrations. It would allow us to describe the changes to the database in code, rather than documentation; it would allow for automatic schema updates on deployment to WildFly; and it is part of the Java ecosystem. In theory, it should also help us (or at least let us try to) stay database-neutral, rather than keeping us tied to PostgreSQL.

It can also be used standalone (ie, outside a Java application), so once we get it set up in the PSM app, if we like it we should update the external data sources app(s) to use Liquibase, as well.

**Comment by cecilia-donnelly** [comment]
@slifty: looks like this is the issue for making a real migration system.  

@slifty and I talked about this continuing to be a problem, in particular as we are making more changes to the kind of information that we store (e.g. in #740).

**Comment by slifty** [comment]
During our team meeting today @jasonaowen brought up the excellent point that as we explore migrations we should think about how to handle different database setups for different branches.  For example, if two in-development branch have schemas that might not work together (e.g. two different table structures).

As part of this task I will try to think through when this might manifest into development blockers, and how that risk can be mitigated through our migration infrastructure.

**Comment by slifty** [comment]
Regarding the branch schema management: after doing some digging it looks like the recommended best practice there is to manually run the appropriate migrations and rollbacks for your branches as you switch.

If this turns out to be too burdensome, a more engineered solution would rely on git hooks that identify new change sets from each branch and run the migrations or rollbacks from the change sets as appropriate.

For instance: switching from branch A to branch B would involve running the rollbacks from A and then running the migrations from B.

I recommend we start with a manual approach--this is status quo anyway / the same as what we do without migrations--and only consider the more complex / automated approach if it is considered a priority.

**Comment by slifty** [comment]
Liquibase allows you to write migrations in four formats: XML, YAML, JSON, SQL.

I narrowed the choice to be between SQL and XML simply because it didn't seem like YAML or JSON offered much benefit.  SQL feels easier to read and write / would leverage the sql we have in `seed.sql` already, but XML seems more robust and "honest" (SQL might mislead folks into thinking they could just run the migration sql file; I also believe that liquibase SQL is a slightly more generic flavor than what we use in seed.sql).

The Liquibase documentation is written in terms of the XML flavor.

Currently planning to use XML for our migrations, but would appreciate any feedback cc @jasonaowen @PaulMorris 

I would also like to discuss the commit / PR strategy for these migrations so as to avoid large commits.  I'll take that conversation offline and report back here.

**Comment by jasonaowen** [comment]
> Liquibase allows you to write migrations in four formats: XML, YAML, JSON, SQL.
> Currently planning to use XML for our migrations

I agree with this. YAML and JSON are perhaps a little easier to read, but it seems they would require adding an additional jar to our build, and we don't really have very much of either elsewhere in our project - in contrast with XML, particularly for configuring Java things. I agree with the concern about Liquibase-SQL, and I appreciate the benefit of the documentation using XML.

**Comment by PaulMorris** [comment]
I agree that XML would a good way to go.

**Comment by jasonaowen** [comment]
We'll need to figure out a good way to run the migrations on our CD server; currently, we build the application on Jenkins, [copy it](https://github.com/SolutionGuidance/psm/blob/6abec5a8d310d0af0ff6ca1f3202faa03fe274b8/scripts/deploy-ci.sh), and [deploy it](https://github.com/SolutionGuidance/psm/blob/6abec5a8d310d0af0ff6ca1f3202faa03fe274b8/scripts/deploy-server.sh) - the source code is never copied to the CD server, and the build server never has access to the database. We've been running migrations by hand so that we don't lose the data our test users have created.

It seems that for Liquibase to even generate migration / sync SQL, it needs to be able to connect to the database, so I guess we'll need to set up a port-forwarding SSH tunnel or something to allow Jenkins to connect with the database on the CD server. @slifty, I think you set up CD initially; do you have any thoughts on this?

**Comment by slifty** [comment]
@jasonaowen My first thought was the same as yours, but exposing that service to the net does feel a little something (port-forwarding SSH is probably the safest bet).

Another thought that crossed my mind was rsync-ing the db project / directory, installing liquibase directly, and running the migrations that way.

If we were to do automated migrations I assume this would be a moot issue because the migration files would be packaged and run directly...  Maybe we should do the "easiest" thing for now (probably the SSH tunnel) and then commit to a mutual automated migration approach?

**Comment by jasonaowen** [comment]
@slifty we mentioned in #908 that we were leaving behind `seed.sql` to make sure not to mess up our CI, but it turns out that past-us were fairly clever:

```bash
if [ -f db/seed.sql ]
then
  cat db/seed.sql | psql -h localhost -U psm psm
fi
```

We can delete `seed.sql` whenever we're ready and there should be no ill effects.

**Comment by slifty** [comment]
We decided to break out the jbpm.sql transfer from this issue, since the future of jbpm is unclear for this project.  Getting rid of jbpm.sql is being moved into a new issue.
