### ISSUE TITLE
Can't paste into NPI field

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#336]
What it says on the TIN.  We shouldn't be forcing users to memorize their NPIs, especially since leaving the input with a half-entered NPI means the app deletes the already-entered information (we shouldn't do that, either).

**Comment by cecilia-donnelly** [comment]
The same is true of the FEIN field, but apparently not the SSN.  @PaulMorris suggests this may have something to do with the event handlers on the inputs.

**Comment by PaulMorris** [comment]
I've investigated this a bit.  It appears to be caused by the "Masked Input" plugin[0] for jQuery that we are using.  It's what gives our input fields the underlines and slashes that match the shape of the input, and limits them to a certain number and/or type of characters, etc.  

We are on an older version of the plugin (1.3.1, the current version is 1.7.7).  And there was a bug[1] with pasting in the older version, but it appears to have been fixed[2].  So upgrading this plugin looks like the best next step forward.  It requires jQuery >= 1.5 and we're on 1.7.1, so we should be able to upgrade the plugin without upgrading jQuery.

[0] https://plugins.jquery.com/mask/
https://github.com/igorescobar/jQuery-Mask-Plugin
https://igorescobar.github.io/jQuery-Mask-Plugin/

[1] https://stackoverflow.com/questions/14509384/jquery-masked-input-plugin-doesnt-accept-paste#14509714
[2] https://github.com/igorescobar/jQuery-Mask-Plugin/issues/186

**Comment by PaulMorris** [comment]
Oh, wait, there are two plugins: "Mask" and "Masked Input"
https://plugins.jquery.com/mask/
https://plugins.jquery.com/maskedinput/

We're using "Masked Input" but "Mask" is the more active of the two and has the fix for pasting issues.  ("Masked Input" has links for its homepage and author that don't work.)  So perhaps we should look into switching to "Mask" from "Masked Input"?

**Comment by PaulMorris** [comment]
Looks like the npm page for "Masked Input" is more well maintained than its plugins.jquery.com page (but that the two are out of sync doesn't inspire confidence):
https://www.npmjs.com/package/jquery.maskedinput
"Masked Input" was last published to npm 2 years ago, current version 1.4.1 (we are at 1.3.1).  21,962 downloads in the last month.

Ah, looking at the github page linked from the npm page:
https://github.com/excellalabs/jquery.maskedinput
It's a fork, by excellalabs, of the original repo by digitalBush, and the original repo says:
"This repository has been archived by the owner. It is now read-only."  
So that explains some things, like why the digitalBush website for the plugin is a dead link.

Compare with the "Mask" npm page:
https://www.npmjs.com/package/jquery-mask-plugin
"Mask" was last published 2 weeks ago.  58,186 downloads in the last month.
Both plugins' repos have about 30 or so contributors.

"Mask" appears to offer more features, but the basic functionality (that we are using) appears to be the same, even very similar APIs.  Just different characters used for the mask patterns.

Masked Input -> Mask
a -> S (letters)
9 -> 0 (numbers)
\* -> A (letters or numbers)

Our JS uses the `.mask` method, with only the first parameter, about 40 times in straightforward ways, so converting syntax should be easy.  

All considered, I'm thinking we should switch to "Mask".

**Comment by PaulMorris** [comment]
Just to cover all bases, I tried the most recent version of "Masked Input" (1.4.1) to see if it fixed the pasting problem.  It didn't, so all the more reason to switch to the "Match" plugin.
