### ISSUE TITLE
Improve UI in screening log

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#355]
I appreciate the explicit message in "Status: SUCCESS ... No records were matched". When we do find a match, I would love for that screen to explicitly also say, under "Status: SUCCESS" something that parallels the "no records" phrasing, e.g., "At least one record was matched", on its own line, before the NPI and other details of the matched record.

(This was previously a comment on #345.)

**Comment by brainwane** [comment]
Also, I'd welcome some better UI to show the number of matched records, visually distinguish the header from the content, and so on.

**Comment by brainwane** [comment]
Related: #356.

**Comment by jasonaowen** [comment]
@brainwane did #364 address this, or is there more to do? Would you please look at the screenshots in that PR and then either say what is left, or close this issue?

**Comment by brainwane** [comment]
@jasonaowen I believe the remaining TODO from this issue is to better distinguish the summary from the detail, e.g., to visually separate "3 records matched" from the list of those records.

**Comment by jasonaowen** [comment]
Oh right, the `<hr>`s are rendered strangely. @PaulMorris, this could be a good thing for you to work on!

**Comment by PaulMorris** [comment]
Thanks @jasonaowen !  I've assigned myself to it.

**Comment by jasonaowen** [comment]
@Paul Morris and I spoke yesterday about the automatic screening log page; I think it needs to change as part of the screening persistence work (#761), and we came up with a plan I'm happy with:

- if there was no screening performed, there is no link from the admin review page
- if there was an error, there is no link from the admin review page, for now - later we should persist the error and, possibly, present it to the reviewer; a stack trace is never a user-friendly UI, but these are internal customers and probably would rather know the nature of the error than have a generic "bzzt"? But, either way, out of scope right now, since we're already not persisting the error in the JAXB XML representation.
- if the LEIE screening result was good, there is a link (later to turn into a modal, perhaps?) to a page that shows when it was run, that the result was "pass", and the NPI searched for. (Other screenings would have other data shown, probably).
- if the LEIE screening result was bad, there is a link (again, maybe a modal someday?) to a page that shows when it was run, that the result was "fail", the NPI searched for, and each of the matching exclusions

**Comment by cecilia-donnelly** [comment]
After a conversation with @PaulMorris today, I'll write up some more detail on what I'm looking for in this issue.

The page at issue here is the "screening log" that shows up when an admin clicks "view results" on the review page, to see the results of an automated screening.  Right now, it looks like this when the provider does not appear in the LEIE:

![screenshot-2018-5-8 screening log](https://user-images.githubusercontent.com/1497818/39781165-fe106724-52d3-11e8-821f-3ddeec89dcf1.png)

And like this when the provider does appear in the LEIE:

![screenshot-2018-5-8 screening log 1](https://user-images.githubusercontent.com/1497818/39781605-4777a750-52d5-11e8-8eac-f6a540113d55.png)


(We only have the LEIE set up so far, but presumably it would look relatively the same for other external sources.)

To make this less confusing for a person looking at the page for the first time - an administrator, or even someone just seeing a demo of the PSM - I'd like to make the following changes:

- [ ] Change the title to include the exact external source that was checked and exactly what we're seeing.  So, instead of "External Source Screening Log," use "Results from Automated LEIE Search" or similar.
- [ ] Remove the "Status" from whether or not the search/connection to the source worked or not.  Instead, show "Result: This provider does not appear in the LEIE and may be approved," "Result: This provider appears in the LEIE and should be rejected," or "Result: A connection error occurred.  [Try again](button/link to rerun the automated screening, which will not work yet but may as part of #740) or [search the LEIE manually](link to LEIE search page)."  I'm definitely open to rephrasing these!
- [ ] Do not show "no records were matched" for the case where the provider doesn't appear in the LEIE.
- [ ] If the provider does appear in the LEIE, show the matching records (which we do now).  I think we could do better with presentation here - maybe bold the field names, show the provider's information next to the matched LEIE information, etc.  This is the least urgent improvement, since I think the others will make it more clear what is being shown.

Please let me know if any of this is unclear, @PaulMorris!  We also may show this information in a modal on the review page, instead of opening this page in a new tab.
