### ISSUE TITLE
Make user help docs reliably user-visible

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#359]
Ideally, our user help docs in `psm-app/docs/userhelp/` will be user-visible in all deployed instances of the application.

- Bundle the built user help docs into the application, and give them a reasonable URL (such as `/cms/help`).
- ~~~Integrate Sphinx build into Gradle build process (create a new `docs` project in `build.gradle` and then add a step for the `cms-web` project to always compile the `docs` project)~~~ See #381

(Followup to #311 and #329.)

**Comment by jasonaowen** [comment]
The second task has been split out into #381.

**Comment by cecilia-donnelly** [comment]
@kfogel and @brainwane discussed this briefly, including a summary from @brainwane:

>I suppose I've been imagining:
>    the "Help" link at the top of the screen goes to a page or subsite where the user can read the manual in HTML

@jasonaowen, does this explain it enough?  [The manual](https://solutionguidance.github.io/psm/userdocs/html/index.html) is currently being built on the `gh-pages` branch.  I'm not sure how  hard it would be to build it into the PSM app itself and display it at `cms/help` or similar.

**Comment by jasonaowen** [comment]
That feels fairly straightforward to me:

1. Add the user docs build as a dependency of cms-web
1. Stage the built docs into the cms-web's build dir, to be included in its output `.war` file
1. Update the target of the "Help" link in the header (see also #154)

It doesn't address what, if anything, we're going to do with the dynamic help subsystem (see also #396); that doesn't have to be done as part of this issue, of course, but I would feel better having an answer to that question before making changes, so that we can think about the impact those changes would have on that plan.
