### ISSUE TITLE
Save subcontractor name

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#360]
The flow for organizational provider types includes a page for "Business Ownership or Control Interest."  If you choose "Subcontractor" in the "Type" dropdown then a "Name Subcontractor" label and input field appear.  This is all fine, but if you then choose "Save as Draft," the subcontractor name is not saved.  It also does not appear on the summary page.

I think the name is just never inserted into the database.

**Comment by cecilia-donnelly** [comment]
I tested this on master today and it is still a problem.

**Comment by cecilia-donnelly** [comment]
When I hit "Next" (instead of "Save as Draft"), I can see that the subcontractor name is not populated in the summary tab.


![screenshot-2018-3-5 summary information](https://user-images.githubusercontent.com/1497818/36996387-58996efa-207c-11e8-924a-cea9485a224f.png)

**Comment by jasonaowen** [comment]
I've found the bug and have a fix for it locally, but it's not at all clear to me what the purpose of the field is, or what we would expect users to enter into it. We ask for, and save, the subcontractor's "Full Legal Name"; how would that differ from "Name Subcontractor"?

![subcontractor-name](https://user-images.githubusercontent.com/1494855/37685501-15c206e2-2c6a-11e8-8466-82dcd84d23ca.png)

I ask because it's not clear to me how to title this information when adding it to the summary display! I'll start with "Name Subcontractor", but that doesn't feel very descriptive to me.

Do we need it? Can we remove it?
