### ISSUE TITLE
Fix or remove provider type creation/deletion

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#41]
If you log in as a service admin, there is a button to `Add Provider Type`. Clicking on it produces a stack trace, because several attributes of provider types were removed in 8b28ccfd75bd3b37f6fd93bdcd31e24174633ee2 in response to [#34 Edit Provider Type to add required additional documentation- Service Admin](https://github.com/NASA-Tournament-Lab/coeci-cms-mpsp/issues/34) and [#90 Accepting Provider Agreement](https://github.com/NASA-Tournament-Lab/coeci-cms-mpsp/issues/90).

There is also some complexity around matching the entries in the database to the entries in [an XML file](https://github.com/OpenTechStrategies/psm/blob/a89616ba8deff7f73390f2b0dc32f9b62f3c6954/psm-app/cms-business-model/src/main/resources/Entities.xsd), which may prevent new provider types from being added and needs further research.

Additionally, there is UI around deleting provider types, but it is permanently disabled: there is no backing database column, so everything defaults to undeleteable.

Regardless, either creating new provider types and deleting old provider types should be fully functional, or we should accept that it requires code and/or database changes and remove the broken UI.

![provider types](https://cloud.githubusercontent.com/assets/1494855/26410646/e85e7dbe-4071-11e7-925e-e2d9123fc6b5.png)

**Comment by slifty** [comment]
In addition to the UI side of things, it is worth noting that there is currently [code-level enforcement](https://github.com/OpenTechStrategies/psm/blob/48de8b5666c65b9c9da6765909c557ba46a514eb/psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/LookupServiceBean.java#L113-L120) that descriptions of provider types must be unique.

As discussed in the comments of #49, it is unclear that this is an actual requirement vs simply being a desire to simplify an object interface to return a single object instead of a list when looking up by description.

This should be evaluated when we reconsider the requirements around Provider Type.

**Comment by cecilia-donnelly** [comment]
Coming back to this to say that I think this falls on the "fix" side -- users are going to want to be able to update the list of providers.  

The fix will be fairly complex.  New types will have new rules associated with them -- licenses &c that need to match the new provider type.  I think @jasonaowen and @jvasile have had conversations about updating these rules through a GUI.

**Comment by brainwane** [comment]
When we fix this, we should update the relevant documentation in `psm-app/docs/userhelp/source/service-admin-help.rst`.

**Comment by frankduncan** [comment]
After a conversation with @jasonaowen, the consensus is that the Provider Types should move away from having an enum in the xml.  I'm going to move ahead and fix this issue, leaving #946 open for fixing the eventual breakages that may arise from giving users the ability to edit/add/delete provider types.  During the time when this is fixed and #946 is not, it is possible for subtle bugs to arise if people are aggressive with using this feature.
