### ISSUE TITLE
Review documentation to add relevant contextual help links

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#422]
Per https://github.com/OpenTechStrategies/psm/pull/382#discussion_r135878148 by @kfogel:

> make a quick scan over all of the current documentation, looking for places where it discusses a specific part of the user interface, and for those places, note (either there or in an issue) the possibility of a linkback or tooltip or something from that part of the UI to that part of the documentation.

**Comment by PaulMorris** [comment]
I've done a scan of the user docs and the PSM site itself looking for places to make links between the user docs and the UI.  The 7 from the user docs would be a good set to start with.

**Looking through the user help docs:**
    
1. What can I do to reduce the risk of delay or rejection for an enrollment?
    ...
    Check the NPPES (National Plan and Provider Enumeration System) website to 
    ensure your NPI status is active

2. What is the difference between a private practice and a group practice?
    On the “Practice Info” page of the enrollment process for individual 
    providers, the site asks you:
        Do you maintain your own private practice?
    If you have an Entity Type 1 (Individual) NPI number, say “yes”. 
    The Center for Medicare and Medicaid Services website has more guidance 
    on your NPI number.
        Are you employed and/or independently contracted by a group practice?
    If you are employed and/or independently contracted by an organization 
    health care provider that has an Entity Type 2 (Organization) NPI 
    number, say “yes”. The CMS website has more information on Type 2 NPI 
    numbers and what kinds of business structures should have them.
        
3. How do I input an enrollment for an organization with several individual 
    providers (e.g., a clinic employing several physicians)?
    Choose the correct organizational provider type during the first step of
    enrollment. On the member entry screen, click the link to add an additional 
    member. Repeat as necessary to add all the individuals who will provide 
    services under the umbrella of the organization.      
            
4. What do I do if none of the provider types seem to describe what I do (what 
    this provider does)?
    Contact your state Medicaid office directly.
    
5. How can I update an existing organizational enrollment to add a new provider 
    (e.g., if a clinic hires a new physician)?
    If an enrollment is a draft (you haven’t submitted it yet), then yes, you 
    can click on the draft enrollment and edit the member list.
    If you have already submitted the enrollment, then you should have the 
    individual, or a service agent, create a new enrollment for an individual 
    provider. On the “Practice Info” screen, the user should say “Yes” to the 
    question “Are you employed and/or independently contracted by a group 
    practice?” and enter the organization’s information.

6. How do I use the enrollment verification process?
    Verification is checking an enrollment with federal or state data sources 
    and visually inspecting the license(s) or certification(s) in a submitted 
    enrollment.
    Click “Enrollments” in the navigation bar and go to the “Pending” tab. 
    Click the “Review” link for the enrollment you want to verify. You’ll see a 
    list of things that you want to verify about the pending enrollment before 
    approving it. Under “Auto Screening”, click “View” or “View Log” to see the 
    “External Source Screening Log,” which will tell you whether the PSM has 
    been able to automatically verify each piece of enrollment data with an 
    external information source. If you are satisfied with that result, or if 
    you go to the government database yourself and manually verify that piece 
    of the enrollment, click the “Verified” checkbox for that row.
    ...
    Go back to the list of pending enrollments and click the NPI/UMPI number to 
    view the enrollment details, and look at the License Info tab. Confirm that 
    the issue and renewal end dates in the image are the same as in the 
    enrollment. If you see any discrepancies, you should reject the enrollment.
    At the bottom of the screen, choose “Reject” or “Approve” as appropriate.
    
7. What’s the difference between an agreement and an addendum?
    Both agreements and addenda are documents meant for the “Provider Statement” 
    step in the enrollment process; they are where you place legal terms and 
    conditions for providers to sign. They are identical in format: each 
    agreement and each addendum has a title and content. You can format and 
    style the format of the content.
    You should create a few agreements to cover the major types of providers in 
    your program, and then use special provider-specific addenda for additional 
    statements that providers need to sign. 


**Looking through the PSM site:**

Entering an enrollment:

Provider Type page:

- Add a doc link or explanation of organization vs individual providers.
    (Ideally, we should have a radio button for individual vs organizational 
    provider, then activate/deactivate a drop down for each, instead of the very 
    long drop down which contains both.) 

Organizational enrollment steps:    

Organization info page:
- NPI?
- Effective date?
- "Doing Business As"?
- Federal Employer ID?
- 1099 address?

Individual Member Info:
- NPI/UMPI?

Ownership Info page:
- What's "Specify Type" for?  Ideally, we should only show this option when 
    'Other' is selected, but at least say "Specify Type if "Other""
- 'Type of individual owner' has "?" link that opens a modal, could go to docs.
- FEIN?

Individual enrollment steps:

Personal Info page:
- NPI has "?" link/modal, could go to docs

Practice info page:
- Group NPI / UMPI (2 places, also under "Additional Practice Locations")
- State medicaid ID
- Effective date? (also under additional practice locations)
- FEIN
- State Tax ID
- Fiscal Year End
- Remittance Sequence
- Reimbursement address
- Group name (under Additional Practice Locations)

For Service Admins:
- Agreement vs Addendum could use an explanation.
- COS could use an explanation

**Comment by PaulMorris** [comment]
Here's an update on help items:

**Looking through the user help docs:**

- What can I do to reduce the risk of delay or rejection for an enrollment?

Done by adding info to NPI modal.

- What is the difference between a private practice and a group practice?

Done with PR #706.

- How do I input an enrollment for an organization with several individual
providers (e.g., a clinic employing several physicians)?

- What do I do if none of the provider types seem to describe what I do (what
this provider does)?

Rework these for a new help item for the Provider Type selection help modal to cover these two topics, linking to the second one in the help docs at the end of the modal text.  (This will be a reworked PR #710 )

- How can I update an existing organizational enrollment to add a new provider

Add a "?" link next to the "Actions" heading in the various tables, and have that open a modal "Why can I edit or view some enrollments and not others?".  Also add greyed-out help and view links so each row has both, either greyed-out or an active link.

- What’s the difference between an agreement and an addendum?

Add a "?" link next to the buttons for creating these.  Reword "Add Agreement Addendum" to "Add Addendum".  (Also, the page for editing Addendums needs work as it currently says "Agreement" instead of "Addendum".)


**Looking through the PSM site:**

- NPI/UMPI / Group NPI / UMPI

Add the usual NPI help link/modal.  Practice info page for individual enrollment steps, individual member info for organization steps.  See #655

Ownership Info page:
-  "Specify Type" Ideally, we should only show this option when 'Other' is selected, but at least say "Specify Type if "Other""

- 'Type of individual owner' has "?" link that opens a modal, could go to docs.

Convert existing modal to new system, adding it to help docs.  Give it a good title.

- FEIN?

Just add abbreviation tag to show full text on hovering.

**A few to research and deal with in a subsequent pass:**

Organizational enrollment steps, organization info page:
- Effective Date

Individual enrollment steps, practice info page:
- Remittance Sequence
- Group name (under Additional Practice Locations)

Service Admin:
- COS

From help docs (We are holding off on this one because this UI is up for revision as part of #354.)
- How do I use the enrollment verification process?

**Comment by cecilia-donnelly** [comment]
@PaulMorris, are any of these still outstanding or are they all in open PRs?  (Checking to see whether we can close this issue.)

**Comment by PaulMorris** [comment]
@cecilia-donnelly Once PR #724 lands all those discussed above will be done.  (One not listed above that would make sense: we now have a FAQ explaining "Title V" etc.  It was split off from the previously existing 'Definitions' modal as part of this work.  It would be good to add a help modal wherever "Title V" etc. is used.)

**Comment by cecilia-donnelly** [comment]
@PaulMorris Thanks, and agreed.
