### ISSUE TITLE
Enter key does not submit quick search form

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#618]
If I log in as a provider, click on the quick search text input box, type in a search term, and hit enter, I expect the form to submit and show me the results of the search. Instead, hitting the enter key has no effect, and I have to click on the magnifying glass icon to conduct the search.

**Comment by jasonaowen** [comment]
The enter key *does* work on the system user quick search!

**Comment by PaulMorris** [comment]
So the provider and also admin user quick searches don't actually use a `<form>`, hence "enter" does not work as expected.  These quick searches should be re-implemented so that they use a form, like the system user quick search.  That would also help with #612 which is not an issue for the system quick search.

**Comment by frankduncan** [comment]
I believe this was fixed as part of #779

**Comment by PaulMorris** [comment]
Closing, fixed as part of #779.
