### ISSUE TITLE
Create API that returns a list of approved and/or rejected providers

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#641]
See the [proposed APIs for Poplin](https://github.com/SolutionGuidance/psm/blob/master/docs/Poplin-API-proposals.md).  The first section, call it "Phase 1a," includes:

- Get a list of screened providers
- Get of list of ineligible providers
- Get providers by eligibility date

Our first task is to estimate how difficult this would be.  There is currently a form in the app (visible to admins) that shows provider applicants by their status:

![enrollments-by-status](https://user-images.githubusercontent.com/1497818/35244244-22390004-ff85-11e7-97e9-4ff8acffec4a.png)

We have questions on our side about:
1. Using the `hapi-fhir` library to create an API rather than consume it (currently, the PSM consumes the LEIE API, which was made with `hapi-fhir`). 
2. Using FHIR's "practitioner" resource to represent our providers.

@notpace, @dhill, tagging you so you can easily follow this issue.  Can you link to the SHR spec you showed in our call?  Is it [this](http://standardhealthrecord.org/fhir/StructureDefinition-shr-entity-Practitioner.html)?

**Comment by cecilia-donnelly** [comment]
@jasonaowen and I are estimating this as a public API for the first step.  We expect to add authn/authz in the next iteration.  Poplin is using [oAuth2](https://oauth.net/2/) and [OpenIDConnect](http://openid.net/connect/).

**Comment by cecilia-donnelly** [comment]
Brief notes from call with @jasonaowen just now:
- Practitioner vs. Organization.  Which FHIR resource should we be using?  Practitioner for individuals and Organizations for organizational providers?
- FHIR docs look good -- they're giving us what we need.
- Not doing auth makes this simpler, but it means leaving it in a half-done state.
- Auth wrinkle: changing from anyone can get anything to "some people can get some things"
- Provider using provider credentials shouldn't be able to see everyone's enrollment.  QUESTION: is there a use case where a provider would be hitting the API, or will we only need a system login, for other parts of the MMIS?
- Hit the endpoint, ask for (1) all screened providers, (2) only approved, or (3) only rejected.  
- Likely extension: wrap practitioner/organization into one resource and also indicate enrollment status (approved, rejected, eventually draft, pending).

**Comment by dhill** [comment]
Regarding the FHIR docs, we would like to work with the Standard Health Record (SHR) if at all possible.  The SHR spec can be found at http://standardhealthrecord.org.

**Comment by chj124** [comment]
For us, the info needed by other system will not come from the provider screening module, but from the enrollment module.

The enrollment of a provider to provide services for a human services plan comes after their info is vetted through the PSM. MMIS needs to see that a provider is enrolled in a plan and approved to provide a specific service to verify eligibility. knowing someones application was approved does not work for us.

Also, since we are looking at these modules to fit into a modular approach, the meat of the module, or the "engine" should expose all functionality to allow any UI to access it. Also add in the need for UI fragments so info can be consumed by another page.


looking at the proposed APIs, i have these comments:

    Provider Detail Example APIs:
        Get a list of screened providers
        Get of list of ineligible providers
        Get providers by eligibility date
        Update provider address
        Update provider contact person
        Add provider
        Delete provider

We dont add providers in screening. Anyone can create an account and submit an application.

I can see at the point a providers application is accepted and forwarded to the Provider Enrollment Module the provider would be setup in the Master Provider Index.

We never delete anything, or expose the ability to delete. We should only be setting the status of any applicable information. This brings up the need to enable historical data. All data thats not currently being worked should be moved to a history table. Any historical data that passes an expiration data should be moved into an archival table. Any data exceeding the data retention policy dates would then be deleted. There should also be a way to export/print data in a way to be added to a hard copy storage
option.

providers from the PSM would not have an eligibility date. This would not be when their application was validated and accepted. A provider could have multiple applications in process to provide different services under the same or different plans.

If an application is denied, that doesn't mean the provider is ineligible. They could have applied for additional services which were denied. 

So, Provider Screening Example APIs that make sense initally:
        Get a list of application submitted
                (should include ability for some criteria to select by status)

        Update provider address
                (if PSM connected to the Provider Index, maybe but would need approval, as this isnt necessarily the proper channel to update provider)
        Update provider contact person
                (if PSM connected to the Provider Index, maybe but would need approval, as this isnt necessarily the proper channel to update provider)

Provider information should be added to the Master Provider Index until some information is validated.

Since acceptance of an application is not a guarantee of enrollment, and providers can apply to provide multiple services, to multiple programs, at different times, any at mulltiple facilities, and have additional criteria to meet for enrollment we really view enrollment outside the scope of the PSM.

Additional API commants:

    Eligibility Determination Example APIs: (these would all be part of Provider Enrollment Module PEM)
        Check status of Eligibility Determination
        Get Eligibility Determination
        Update Eligibility Determination
        Delete Eligibility Determination

    Enrollment Example APIs: (these would all be part of Provider Enrollment Module PEM)
        Get Current Enrollments
        Get Historical Enrollments
        Update Enrollments
        Delete Enrollments 

    Appeal Example APIs: (these would all be part of a Grievance and Appeals Module AM)
        Get Current Appeals
        Get Historical Appeals
        Update Appeals
        Delete Appeals

    Audit Example APIs: <- these would be applicable. expose as one call?
        Get Audit
        Get actions taken per user
        Get actions taken per time period
        Get actions taken per provider


What is meant by these APIs? Getting logged communications?

    Messages (Provider Communications) Example APIs:
        Get Messages
        Get Messages per user
        Get Messages per time period
        Get Messages per provider

What about information about publishing and consuming messages through a messaging subsystem like RabbitMQ for an event driven setup?

Ideally, screen broadcasts a message when there is an approved application. Then the PEM could respond to the info, request the application data from PSM (or by using a UI fragment) so an enrollment specialist can continue working with the provider.

i'll stop for now :)

**Comment by cecilia-donnelly** [comment]
@jasonaowen and I spoke to @notpace, @dhill, and Jeff about this. (Pace or Dave, would you link to Jeff's GitHub account, please?  I couldn't find it.)

Here are the takeaways:
- We can use the [Task](https://www.hl7.org/fhir/task.html) resource to represent either a practitioner or an organization - or, in the PSM's terms, an individual or group provider.
- We will first test this API by sending the NPI, name, and address of the provider.  We can expand the dataset later.
- We are deferring authn/authz.  

The next step is for @jasonaowen to write up his initial approach in this issue.  Thanks for the discussion, everyone!

**Comment by jasonaowen** [comment]
As @cecilia-donnelly wrote, the Task resource seems like it will be useful. Initial research on [HAPI-FHIR](http://hapifhir.io/) looks promising, particularly their documentation on [setting up REST endpoints](http://hapifhir.io/doc_rest_server.html). I'm going to start prototyping that.

I am currently thinking of something like this:
- `GET /applications/{application_id}` - retrieve a single enrollment application by ID
- `GET /applications/` - get a list (using FHIR paging) of approved, rejected, and pending enrollment applications. I suggest that draft enrollment applications should not be included here.
- `GET /applications/?status=rejected` - get a list (using FHIR paging) of rejected enrollment applications- `GET /applications/?status=accepted` - get a list (using FHIR paging) of approved enrollment applications. Note that the `accepted` status is a FHIR-ism, rather than a PSM-ism
- `GET /applications/?status=rejected` - get a list (using FHIR paging) of rejected enrollment applications

Each of these will return one or more [Task](https://www.hl7.org/fhir/task.html)s, with the following fields filled out:
- `identifier` - the enrollment application ID. Note that this is not the NPI, as a single provider may need to apply to enroll multiple times for different services.
- `status` - one of `Requested`, `Accepted`, `Rejected`
- `intent` (required by FHIR) - `proposal`
- `requester` - a reference to either a `Practitioner` (individual provider) or an `Organization` (group provider)

A [`Practitioner`](https://www.hl7.org/fhir/practitioner.html) will have:
- two `identifier`s - NPI and SSN
- `name`
- `address` (of their private or primary practice)

An [`Organization`](https://www.hl7.org/fhir/organization.html) will have:
- `identifier` - NPI
- `name`
- `address`

This plan might change as I learn more through implementing it. Please let me know if you have questions, suggestions, or concerns.

**Comment by notpace** [comment]
@cecilia-donnelly Jeff's github account is @jeffro46

@jasonaowen A few comments/questions on that approach:
* Are there any circumstances in which the `Organization` would use an EIN or TIN for an identifier instead of an NPI?
* Is the PSM collecting phone/fax/email that we could put in the `telecom` attributes for `Practitioner` and/or `Organization`?
* External users are more likely to know the NPI than the `application_id` - can we add a `GET /applications/{npi}` to retrieve a single enrollment application by NPI?
* I realize that provider types vary across states , but it might be appropriate to add an extension to capture that type as a codeable concept on the `Practitioner` resource

**Comment by jasonaowen** [comment]
@notpace Thanks! Those are good pieces of feedback.

1. > Are there any circumstances in which the `Organization` would use an EIN or TIN for an identifier instead of an NPI?

    Yes! Good catch. Currently, in our system, the Personal Care Assistant individual provider type does not have an NPI; in that case there would be only the SSN. We also have a few provider types that have the Minnesota-specific UMPI, [Unique Minnesota Provider Identifier](https://www.allacronyms.com/umpi/Unique_Minnesota_Provider_Identifier); I've opened #655 to track that issue). I'll include the FEIN when I have it.
2. > Is the PSM collecting phone/fax/email that we could put in the `telecom` attributes for `Practitioner` and/or `Organization`?

    It is. I left it out of the initial design because it makes it harder to implement, but does not feel particularly risky or likely to cause major design changes. How important is getting telecom information in this first iteration?
3. > I realize that provider types vary across states, but it might be appropriate to add an extension to capture that type as a codeable concept on the `Practitioner` resource

    You're right! I think we could include that information in an `input` element on the `Task`; would that work for you?

**Comment by notpace** [comment]
On telecom: I don't think it's critical to include in the first iteration, but if it's not particularly risky (or time-intensive), it would be nice to have.

On provider types: An `input` on the `Task` resource sounds like a good place for it, especially if it isn't something that is inherent to the provider. Is it common for a provider that works across state boundaries to have two different types on two different applications?

**Comment by cecilia-donnelly** [comment]
>Is it common for a provider that works across state boundaries to have two different types on two different applications?

@notpace The case we've been imagining is more like, a provider works at as a surgeon at a hospital on Fridays, but Monday-Thursday they're a general practitioner of some kind at a clinic.  I don't know how common that is, but any provider that fills two different roles like that would need to fill out two different applications in the PSM.

**Comment by notpace** [comment]
Yeah, that's what I was getting at. If the provider type is inherent to the provider (regardless of application), it would make sense to hang it off of the `Practitioner` resource, but it sounds like it's specific to the application, so it makes sense in the `Task` :)

**Comment by chj124** [comment]
Commenting on the FHIR TASK discussion by @jasonaowen and to API note by @cecilia-donnelly 

I know there is a push to use a standard like SHR or FHIR, but I am not convinced they have a place here as they exist today. 

The Task resource is in the workflow domain which could make some sense in some areas but it is also set for Trial-Use.

Should we want to use any objects that are have not moved past beta use?

**Comment by chj124** [comment]
How will we be able to track the specific services/procedures a provider has applied for?

What if a provider applies to provider x, y, and z but the application approves only x?

**Comment by chj124** [comment]
To the comments about EIN/NPI from @jasonaowen @notpace 

Definitely. We have providers that we approve for non-healthcare services like childcare, transportation, etc.. and these do not have an NPI

**Comment by cecilia-donnelly** [comment]
> How will we be able to track the specific services/procedures a provider has applied for?
>What if a provider applies to provider x, y, and z but the application approves only x?

@chj124 they'll enter a new application for each provider type, and the API would be able to track each of those separately.  We don't have a way to approve individual subspecialties within each type at the moment.  I know Vermont has needs around approving a provider+facility pair for specific procedures.  The PSM doesn't have a way to handle that yet.  We'd need to set that up in the PSM before determining how to represent it in the API.  Can you share an example procedure?

**Comment by cecilia-donnelly** [comment]
Getting back to some earlier comments by @chj124:

>I know there is a push to use a standard like SHR or FHIR, but I am not convinced they have a place here as they exist today.
>The Task resource is in the workflow domain which could make some sense in some areas but it is also set for Trial-Use.
>Should we want to use any objects that are have not moved past beta use?

And

>also, the Task is in the Orders and Observations workgroup which is really outside the domain were working in here

The Poplin team, notably @notpace and @dhill, are using FHIR and we are working to be compliant with them in general and especially for this API.  I'll defer to them on specific questions about FHIR resources and domains - we are following their lead on that.

>also GET /applications/{application_id} would indicate that we are retrieving an application yet i dont see the application represented in the Task contents.

The application is represented by the Task object itself, and the `identifier` of the Task is the `application_id`.

>also, if a provider submits multiple applications, and i want to see what a provider has applied for, i would expect to be able to query with some parameters and get a list of application types and the status of each

Definitely!  We are starting to implement the search with just the `status` parameter (see [this comment](https://github.com/SolutionGuidance/psm/issues/641#issuecomment-362416620)), but will be adding more as time goes on.  (Correct me if I'm wrong, @jasonaowen).

**Comment by notpace** [comment]
@chj124:
> Should we want to use any objects that are have not moved past beta use?
If you're aware of any existing standards that achieve the same thing, I'd love to hear about them.  The less we need to build, the better.  Given the options that I'm aware of, FHIR seems to be a good starting point.

> the Task is in the Orders and Observations workgroup which is really outside the domain were working in here
The `Task` resource originated in Orders and Observations, but it has been left deliberately broad to accommodate general clinical and (for our purposes with PSM) administrative workflow.

**Comment by jasonaowen** [comment]
@notpace from what I understand of FHIR, it seems to expect resources to be located at specific locations based on their type. In particular, since we are using `Task` resources to represent enrollment applications, they should be located under `/Task` relative to the base URL of the FHIR API, instead of `/applications`. Does that sound reasonable to you?

**Comment by notpace** [comment]
Yeah, that's where I would expect it.

**Comment by kfogel** [comment]
Just noting possible relationship with / duplication of issue #623.

**Comment by jasonaowen** [comment]
Continuing conversation from [#670](https://github.com/SolutionGuidance/psm/pull/670#issuecomment-370553196), since that PR has been merged and comments on it might be a little harder to find and keep track of.

> Should there be an active field for practitioner and organization?

I started with the bare minimum, but this is something we can add. It's not clear to me, however, when it should be `true` and when it should be `false`. The information we have about a provider is a point-in-time snapshot: this is what the provider entered when they were applying for enrollment. Presumably the provider is active at that point in time, right? When would that change? Why?

What do you want that field to represent, @dhill? When would you want it to change, and for what reason? Would it encode any information that isn't presented elsewhere?

(For background, here is the documentation for these fields: [`Practioner.active`](http://hl7.org/fhir/practitioner-definitions.html#Practitioner.active) and [`Organization.active`](http://hl7.org/fhir/organization-definitions.html#Organization.active).)

**Comment by cecilia-donnelly** [comment]
@jasonaowen, I believe this was completed in #714.  We'll open a separate issue for returning more information via the API.
