### ISSUE TITLE
Choose front end library / set up for reports

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#753]
We want to display reports (see #739), possibly including some charts/graphs.  Choose a library that fits into our existing build system (we [prefer to keep our set of tools small](https://groups.google.com/forum/#!topic/psm-dev/ZJeNN0ufOYw)) and gives us flexibility to make more reports in the future.

**Comment by jasonaowen** [comment]
I think it would make sense to render charts and graphs on the client side using a JavaScript library. It would probably be easier to do so than to render them server-side, and in particular it would allow us to more effectively divide our labor. This would also allow for easier, faster alteration of the reports - JS would allow for zero or one round-trip to get more data without reloading the page.

Some things we might want to consider in the selection of a JavaScript library for this specific task include:
1. Do users want to print the results?
2. What browsers do we want to support? I don't think we have an official list, but I seem to recall that we want to support Internet Explorer on Windows 7; Wikipedia tells me that IE 10 can be installed on Windows 7, which is hopefully a reasonably recent version when it comes to JS library support.

(@cecilia-donnelly, do you have any insight into either of these?)

**Comment by PaulMorris** [comment]
@jasonaowen I agree on using a client-side JS library, and those are some good questions to consider.  

I looked into the options, and the go-to JS library for this kind of data visualization is [D3.js](https://d3js.org/) (D3 stands for Data Driven Documents).  It's [available on npm](https://www.npmjs.com/package/d3) and will work with our current setup for using JS libraries (like axe-core).  It also supports ES2015 modules so will work fine when we move to a webpack-type setup in the future.  

It works with standard web formats, namely SVG and canvas graphics, providing better APIs for working with them for data visualization, rather than giving you a different abstraction to work with on top of them as some other libraries do.  It simplifies making basic charts and graphs, but is also quite powerful, allowing for dynamic visualizations if needed.  It also can be used in a modular way, only using [the parts of it](https://www.npmjs.com/search?q=d3) that are needed.  So that is an option we could consider.

We should consider the printing and browser compatibility questions, but as long as it meets our needs there, then D3.js is a solid choice for doing charts and graphs in our reports.
