### ISSUE TITLE
Add new fields to FHIR API

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#846]
I'm splitting this out from #623 to allow us to more easily track our progress.

These new fields will be added as `input` elements on the FHIR Task resource:

- [x] EFT acceptance indicator
- [x] provider date of birth
- [x] telecom
- [x] address

Tagging @slifty @mbestavros @notpace.

**Comment by slifty** [comment]
A new question for @notpace  around the EFT Acceptance.

- EFT acceptance is a flag that can be set on an [Organization](https://github.com/SolutionGuidance/psm/blob/master/psm-app/services/src/main/java/gov/medicaid/entities/Organization.java#L208)
- The field that links an Enrollment to an organization is the [Affiliations list](https://github.com/SolutionGuidance/psm/blob/master/psm-app/services/src/main/java/gov/medicaid/entities/ProviderProfile.java#L164)

An enrollment can have more than one affiliation; affiliations can be listed as "primary" -- I believe there is only one primary affiliation, though I could be wrong.

My question is: should an enrollment be considered as accepting EFT if and only if the primary affiliation accepts EFT, or should it be if *any* affiliation accepts EFT.

**Comment by notpace** [comment]
Excellent question.  After talking with some of the MMIS certification folks, they have found that most industry products interpret the requirement for EFT acceptance to be related to a provider's primary affiliation.  E.g., a provider that primarily works for a small physician group practice that *does not* accept EFT but performs occasional work for a larger hospital system that *does* accept EFT would have that flag set to false.

**Comment by jasonaowen** [comment]
It turns out that sometimes we don't have data we want to expose in the API. One example of that is that [we don't always ask if an organization accepts EFT](https://github.com/SolutionGuidance/psm/issues/411#issuecomment-352091723). We need to figure out how best to represent that fact in what our API returns.

We have a few options:

- simply don't include the data in the output for enrollments that don't contain that data
- have a default for when we're missing data
- somehow encode the fact that the data is missing, and maybe even why

For that last option, we've found the [yes-no-unknown value set in SHR](http://standardhealthrecord.org/fhir/ValueSet-shr-core-YesNoUnknownVS.html) (which it seems we might not be able to easily use with HAPI-FHIR, or at least it's not yet clear to me how to do so), and the [data absent reason value set](http://hl7.org/fhir/valueset-data-absent-reason.html). @notpace [suggests](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/FHIR.20Test.20Endpoint/near/43699):

> That data absent reason CS/VS is normally useful as a child element of a data element that has a considerable amount of structure. Since our "EFT Accepted" indicator is meant to be less verbose, I don't think we want to build a hierarchy just for it

We are leaning towards the first option (don't include missing data); are there any concerns about this approach?

**Comment by notpace** [comment]
@jasonaowen I haven't worked directly with HAPI, but I have a hunch that the [yes-no-unknown value set in SHR](http://standardhealthrecord.org/fhir/ValueSet-shr-core-YesNoUnknownVS.html) can be represented as a [CodeableConcept in HAPI-FHIR](http://hapifhir.io/doc_fhirobjects.html#Open_Valusets__CodeableConcepts).  It is likely that we'll need to include other CodeableConcepts for custom Value Sets with other `input` fields, so this could be a good test drive.

**Comment by jasonaowen** [comment]
> I haven't worked directly with HAPI, but I have a hunch that the [yes-no-unknown value set in SHR](http://standardhealthrecord.org/fhir/ValueSet-shr-core-YesNoUnknownVS.html) can be represented as a [CodeableConcept in HAPI-FHIR](http://hapifhir.io/doc_fhirobjects.html#Open_Valusets__CodeableConcepts).  It is likely that we'll need to include other CodeableConcepts for custom Value Sets with other `input` fields, so this could be a good test drive.

@notpace ah nice! I was looking for existing code around that value set, as there is for the example `MaritalStatus` enum in that link, and not finding any; it's super helpful to know how to do it manually - thank you! I or @slifty will work on that after #882 is merged.

**Comment by jasonaowen** [comment]
> I did have a few questions around which specific information we should be pulling for some of the fields. I've chatted with @notpace offline about some of these; he suggested that I throw the discussion up here so others (@jasonaowen @slifty ) and the public can see this discussion.

Hi @mbestavros! This is absolutely the right place to have this conversation, so thank you for raising it here. Even if the conversation mainly ends up being between you and @notpace, having it recorded will help everyone understand the context and decisions.

Our API is driven, at least in part, by the Project Poplin integrations that will depend on them. What data to include first, and how to structure that data, has been informed in large part by @notpace. We've been adding data iteratively, both to get the foundation in place so that others can build upon it (like you!) and because there is value in providing partial information.

I think our plan is to include as much data as possible in a way that makes sense. So, broadly, my answer to your questions is going to tend to be "both", or at least "one now, and a plan for more later". @slifty and I am probably going to be more useful in answering "how" questions than "what" questions.

> I've made the assumption that, for the purposes of the API, we are only interested in the Primary Office location's address, and that it's OK to ignore the alternate addresses if they exist. If this should be different, do speak up.

The primary office address makes sense as a first step. How do you intend to include that in the response? How would you add the alternate addresses later? Remember that it's generally best to alter APIs by adding additional fields without removing existing fields, as it's easy for clients to ignore unrecognized data and hard for clients to handle missing data (or at least, data not being in the place they expect it to be).

> Given [the "Contact Phone Number" and "Primary Office's phone number"] phone numbers, which one should we be returning in the API? Just the Primary Office number, which is mandatory and therefore we are guaranteed to have? If a Contact Phone Number exists, use that one? Would it be possible to return both? Would love to hear opinions.

Same questions: How do you intend to include phone numbers in the response? How would you add additional numbers later?

> I've been working on adding the remaining fields into the API, and I've made good progress. Provider date-of-birth and address are both hooked up and seem to be working, though I still need to write tests for them.

We like small pull requests! Please consider splitting the work around one particular field (such as date-of-birth) out into its own branch and open a pull request. That'll let us give you more concrete feedback on your approach, which you might be able to apply to the work you do on the other fields.

**Comment by notpace** [comment]
> broadly, my answer to your questions is going to tend to be "both", or at least "one now, and a plan for more later"
Agreed.  We haven't explicitly covered the cardinality for these fields with the Poplin members working on Provider Screening, so it's helpful to figure out the architecture that supports the widest possible implementation and narrow it from there.

A broader note about phone numbers and addresses: these are generally modeled as `0..*` elements in the base [Practicioner](https://www.hl7.org/fhir/practitioner.html) and [Organization](https://www.hl7.org/fhir/organization.html) resources, so the restrictions on type and amount of addresses will be driven by business need, if at all.

**Comment by mbestavros** [comment]
> How do you intend to include that in the response? How would you add the alternate addresses later?

The Practitioner structure that we're currently returning in the API has fields for both Address and Telecom, so I'm just adding the additional fields to the existing structure. There is some translation involved between the in-house data structures we use and the HAPI-FHIR structures for those fields, but all the important data is preserved between the structures. The only thing we don't keep is ID, which @notpace and I thought was not important to return as part of the API.

Specifically talking about implementation, HAPI-FHIR takes lists as input for these fields, so it shouldn't be too difficult to add multiple addresses or phone numbers if we want to. The challenge we need to think a bit about is how to identify one address or phone number as "primary;" as far as I can tell, there's no way to distinguish that within the HAPI-FHIR structures.

**Comment by jasonaowen** [comment]
> The challenge we need to think a bit about is how to identify one address or phone number as "primary;" as far as I can tell, there's no way to distinguish that within the HAPI-FHIR structures.

That's specifically what I was concerned about. I think it applies both to addresses (personal, primary practice, alternate practice, billing, 1099) and to phone numbers (contact, practice, office, fax); if we don't include the purpose of the address or phone number, I'm not sure it's very useful.

I see [ContactPoint](http://hl7.org/fhir/datatypes.html#ContactPoint), which may include a [contact point use](http://hl7.org/fhir/valueset-contact-point-use.html), but the values in that value set don't seem to correspond to our needs at all.

@notpace how would this information best be represented in FHIR?

> The only thing we don't keep is ID, which @notpace and I thought was not important to return as part of the API.

I agree with that. :+1:

**Comment by mbestavros** [comment]
As an addendum to my previous comment, I've gotten the API returning all addresses entered within the standard Practitioner structure and HAPI-FHIR--further pushing the real problem onto an identification of purpose.

A quick look at [the FHIR Address documentation](https://www.hl7.org/fhir/datatypes.html#Address) doesn't leave a whole lot of room for additional information. My first thought was that we might be able to use the `text` field to encode purpose, but the documentation precludes that idea:

> The text element specifies the entire address as it should be represented. This may be provided instead of or as well as the specific parts. Applications updating an address SHALL ensure either that the text and the parts are in agreement, or that only one of the two is present.

Bit of a dilemma. @notpace , any ideas?

**Comment by notpace** [comment]
Unfortunately, since [ContactPointUse](http://hl7.org/fhir/valueset-contact-point-use.html) is tightly bound to the [ContactPoint](http://hl7.org/fhir/datatypes.html#ContactPoint) datatype, we cannot use another value set for `ContactPoint.use`.  Same thing for [Address](http://hl7.org/fhir/datatypes.html#address) and [AddressUse](http://hl7.org/fhir/valueset-address-use.html). 

_**If**_ we need to further specify a custom value set for why those addresses exist, we can create a custom value set and use a FHIR extension to capture the possible values as a `CodeableConcept`. 
 I emphasize "if" because this is all dependent on whether the Provider Management module needs this level of detail from Provider Screening.  We need the Poplin working group members to weigh in on this.

**Comment by notpace** [comment]
If you want to go ahead with something while we're waiting for feedback (which might be nice as practice regardless), I'd offer a bit of guidance about FHIR extensions - use as much of the base resource as possible before working explicitly with extensions.

For example, with `Address`, you could easily create an `ProviderAddressUse` code set and add it to the address element:

| Address Type from PSM | ProviderAddressUse |
|----------|---------|
|Personal|personal|
|Primary Practice|primary_practice|
|Alternate Practice|alternate_practice|
|Billing|billing|
|1099|1099|

That's fine, but make sure you fill in the traditional `Address.use` value so that a system parsing the base FHIR resource (but not the extension) still gets some semantic information about the Address:

| Address Type from PSM | Address.use | ProviderAddressUse |
|----------|---------|---------|
|Personal|home|personal|
|Primary Practice|work|primary_practice|
|Alternate Practice|work|alternate_practice|
|Billing|work|billing|
|1099|work|1099|

**Comment by jasonaowen** [comment]
@notpace that's helpful, thank you! @mbestavros, is that enough to get you started?

**Comment by mbestavros** [comment]
Hopefully! I've been working on laying the groundwork for the Telecom field in the meantime.

I'll need to do my own research into codesets (or just have @notpace explain it to me when he has the time).

**Comment by mbestavros** [comment]
@jasonaowen @notpace It looks like we can avoid this issue with Telecom: the [`ContactPoint`](https://www.hl7.org/fhir/datatypes.html#ContactPoint) datatype has a field for `rank`:

> Specify preferred order of use (1 = highest)

> The rank element can be used to specify a preference for the order in which a set of contacts is used. Contacts are ranked with lower values coming before higher values. Note that rank does not necessarily follow the order in which the contacts are represented in the instance.

seems like we could use this to indicate which number is most preferred.

This still doesn't quite answer the initial question of which number we want to be reflected as the primary number; for now, I'm assuming it will be the number of the primary affiliation.

**Comment by jasonaowen** [comment]
> It looks like we can avoid this issue with Telecom: the `ContactPoint` datatype has a field for `rank` ... Seems like we could use this to indicate which number is most preferred.

Most preferred for what purpose? I count at least four different places we collect phone numbers, which are variously labeled contact, practice, office, or fax. Contact phone number would be preferred for asking questions about the enrollment application, practice might be best for scheduling an on-site visit, office for billing questions, and of course fax for sending faxes.

If we have multiple of any one type of those numbers, `rank` would be useful to prioritize within that type, but I don't think it solves the problem of needing to attach the type of the phone number.

I like what @notpace says about extensions. I don't yet understand how that works when it comes to implementation, but I'd like for us to at least try to do that. @mbestavros, have you had a chance to sit down with @notpace and talk about this? Can you look into adding `ContactPointUse` and `ProviderAddressUse` (or whatever) extensions?
